---
- name: restart smb
  service:
    name: smb
    state: restarted
    enabled: true

- name: restart nmb
  service:
    name: nmb
    state: restarted
    enabled: true

- name: config firewall rules
  firewalld:
    service: samba
    state: enabled
    permanent: true
    immediate: true

