---
- name: cofiguring a samba server and client
  hosts: smbserver, smbclient
  become: true
  tasks:
    - name: configuring a smb server 
      include_role: 
        name: samba
      when: inventory_hostname in groups['smbserver']



