---
- name: cofiguring a samba server and client
  hosts: smb-server, smbclient
  become: true
  tasks:
    - name: configuring a smb server 
      include_role: 
        name: samba-server
      when: inventory_hostname in groups['smb-server']



